### ISSUE TITLE
TODO for launch

### ISSUE THREAD

**Issue by alexsavio** [euroscipy/euroscipy.github.io#2]
- [x] fix menu bar to not cover page content
- [x] review FAQ content
- [x] add sponsorship packages page and fix missing icons
- [x] replace venue picture for a picture from BA
- [x] remove all images in the theme that are not being used
- [x] CI/CD

**Comment by oiertwo** [comment]
- [ ] add social elements to index

**Comment by oiertwo** [comment]
I think that we have enough content to go public and publish the initial euroscipy2020 web site. 👍

**Comment by alexsavio** [comment]
Need to make this work now: euroscipy.github.io/

**Comment by pdebuyl** [comment]
Hi all,

I don't track the telegram group very often. I sent an email some time ago to the mailing list and my main criteria (hosting on our static host, keeping redirects, and using "domain/YYYY" for the conference) can be fit with this repo, is this correct?

We need to put "excludes" in the makefile so that a push of this does not delete the former years of static content.

Has anyone "statified" the program of 2019?

**Comment by alexsavio** [comment]
Hi @pdebuyl !

Thanks for the follow up.

I am not sure if @datapythonista statified 2019 in the web server. This is for sure a necessary step before moving to the new theme.

Maybe a redirect in the webserver to this also makes sense, I wouldn't mind either: hosting this in the server or putting a redirect there to this Github Pages setup. Actually I would be more keen on the second option.

Yesterday we were chatting about this and @datapythonista asked you this:
Pierre do you mind creating a user for the server for @alexsavio, and another one to automate the deployments from the CI please? So, depending on how we decide to host it, it would be nice to automate the deployment.

@datapythonista, sorry, I just checked again, and I do have access to the server, but I don't know where the things are.

**Comment by pdebuyl** [comment]
@alexsavio there is a user for you, there even is a ssh directory with authorized_keys. If you don't have a valid key anymore, you can send one to me by email (with gpg if you wish, I'll send you my public key).

I see that we use github workflow. I'll create a user and a key on the server. This seems the easiest as of now and can be changed in the future. What I understand: the current repo is used to push "/2020" to the server, the rest remains untouched, right?

**Comment by alexsavio** [comment]
@pdebuyl I got back the access to the server, but I don't know what I can touch.

If you create the user and the key in the server, I can set the pipeline to push the content of /2020 to the server, I might need to readjust the output path of the theme folder (https://github.com/euroscipy/euroscipy.github.io/tree/master) but this should be possible.

**Comment by pdebuyl** [comment]
theme_2020 would fit.

There is
- feeds : was never used, it is generated by default by pelican
- extra: is this needed? there is an empty CNAME file 
- 404.html we don't have one currently, I see no conflict
- index.html -> this changes the setup. Until now, index.html was a list of all editions. I am in favor of keeping it this way, with a prominent link to the current edition and that www.euroscipy.org/2020 is used for the communication.

**Comment by alexsavio** [comment]
@pdebuyl Thanks for the review, I will change that as soon as I can.
By the way, we are meeting today at 19:00 CET. Would you like to join? I can send you an invite to your email, please send me your address

**Comment by pdebuyl** [comment]
I created a new user with an ssh key, which is now a github secret. Please don't use it before verifying by hand that it works with "rsync --dry-run". I'd like to attempt a "make rsync_upload" myself for validation.

**Comment by pdebuyl** [comment]
I made the changes

- use excludes
- rename the theme to theme_2020

https://github.com/pdebuyl/euroscipy.github.io/tree/archival_compat

a "dry run" seems to work fine.

it remains only to change the index file.

I set the "guid" bit (see https://superuser.com/questions/19318/how-can-i-give-write-access-of-a-folder-to-all-users-in-linux ) for the group euroscipyweb on the server. This should enable several users to push without any ownership clash.

**Comment by pdebuyl** [comment]
I made the changes

- reinstate a generic landing page
- remove CNAME
- add a template landing.html that contains no 2020 information and that does not require metadata

the landing page has a blank style now, as it does not refer to 2020 metadata. It is a bit weird.

Apart from this, I believe that it is ready for deployment. We can do this next week, with the integration to github action.

**Comment by alexsavio** [comment]
That's great! Thanks @pdebuyl! I am improving some changes @oiertwo did on the sponsors_info page and creating the sponsorship signup form.
I will have a look at your landing page issue.
Would you like to make a PR into this repository?

**Comment by pdebuyl** [comment]
This seems ok for publication on the "pelican machinery" side. I would like to do a first push from my computer and then I can setup the actions. I already tested the ssh key access to the server on the branch ssh_test and this should be applicable for the publication as well. The "set guid" bit on the files mean that the group ownership should be preserved on the server.

**Comment by pdebuyl** [comment]
preview: http://pdebuyl.be/tmp/esp/2020/

**Comment by oiertwo** [comment]
website launched. Should we close this issue?

**Comment by pdebuyl** [comment]
Yes. Important remark: the CI pushes automatically the "develop" branch, so look twice before merging!
